services:


  nginx:
    image: moodle-nginx-dev
    build: 
      context: ..
      dockerfile: docker/nginx/Dockerfile
    container_name: moodle-nginx-dev
    ports:
      - "8080:80"
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../docker/nginx/moodle.conf:/etc/nginx/conf.d/default.conf:ro
      - ../moodle:/var/www/html:ro
    depends_on:
       moodleapp:
         condition: service_healthy
    networks:
      - moodle-dev-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  moodleapp:
    build:
      context: ..
      dockerfile: docker/php-fpm/Dockerfile
      target: development
      args:
        ENVIRONMENT: development
    image: moodle-web-dev
    container_name: moodle-web-dev
    ports:
      - 8080:80
    volumes:
      - moodledata-dev:/var/www/moodledata
      - ../moodle:/var/www/html
      - ./custom:/app/custom
    depends_on:
      - postgres
    
    environment:
      ENVIRONMENT: development
      MOODLE_DATABASE_HOST: ${PGSQL_HOST}
      MOODLE_DATABASE_USER: ${PGSQL_USER}
      MOODLE_DATABASE_NAME: ${PGSQL_DATABASE}
      MOODLE_DATABASE_PASSWORD_FILE: /run/secrets/db_password
      MOODLE_WWWROOT: ${MOODLE_WWWROOT}
      DEBUG: 'true'
    secrets:
      - db_password
    networks:
      - moodle-dev-network

  postgres:
    image: postgres:17-alpine
    container_name: moodle-pgdb-dev
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - moodle-dev-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    ports:
      - "81:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    networks:
      - moodle-dev-network

secrets:
  db_password:
    file: ../secrets/db_password.txt

volumes:
  pgdata-dev:
  moodledata-dev:

networks:
  moodle-dev-network:
    driver: bridge 
    